name: Docker Build and Test on Ubuntu

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker build -t vietnam-nlp -f NLP_q1/Dockerfile NLP_q1

      - name: Run NLP Pipeline in Docker
        run: |
          docker run --rm vietnam-nlp

